---
Name: shortcodable
After:
    - framework/*
    - cms/*
---

SilverStripe\Admin\LeftAndMain:
  extra_requirements_javascript:
    - 'shortcodable/javascript/editor_plugin.js'
    - 'shortcodable/javascript/shortcodable.js'
  extra_requirements_css:
    - 'shortcodable/css/shortcodable.css'

SilverStripe\Control\Director:
  rules:
    'admin/shortcodable': Sheadawson\Shortcodable\Controller\ShortcodableController

SSheadawson\Shortcodable\hortcodable:
  htmleditor_names:
    - cms

SilverStripe\Forms\HTMLEditor\HTMLEditorField:
  extensions:
    - Sheadawson\Shortcodable\Extensions\ShortcodableHtmlEditorField

SilverStripe\View\Parsers\ShortcodeParser:
  extensions:
    - Sheadawson\Shortcodable\Extensions\ShortcodableShortcodeParserExtension
