---
Name: shortcodable
After:
    - 'framework/*'
---

SilverStripe\Admin\LeftAndMain:
#  extra_requirements_javascript:
#    - 'sheadawson/silverstripe-shortcodable: client/javascript/shortcodable.js'
  extra_requirements_css:
    - 'sheadawson/silverstripe-shortcodable: client/css/shortcodable.css'

SilverStripe\Control\Director:
  rules:
    'admin/shortcodable': Silverstripe\Shortcodable\Controller\ShortcodableController

Silverstripe\Shortcodable\Shortcodable:
  htmleditor_names:
    - cms

HtmlEditorField:
  extensions:
    - ShortcodableHtmlEditorField

Silverstripe\Shortcodable\ShortcodeParser:
  extensions:
    - Silverstripe\Shortcodable\ShortcodableShortcodeParserExtension

SilverStripe\Admin\ModalController:
  extensions:
    - Silverstripe\Shortcodable\ShortCodeModalExtension
