---
Name: shortcodable
---

SilverStripe\Admin\LeftAndMain:
  extra_requirements_javascript:
    - sheadawson/silverstripe-shortcodable:client/javascript/editor_plugin.js
    - sheadawson/silverstripe-shortcodable:client/javascript/shortcodable.js
  extra_requirements_css:
    - sheadawson/silverstripe-shortcodable:client/css/shortcodable.css

SilverStripe\Control\Director:
  rules:
    'admin/shortcodable': Sheadawson\Shortcodable\Controller\ShortcodableController

SSheadawson\Shortcodable\hortcodable:
  htmleditor_names:
    - cms

SilverStripe\Forms\HTMLEditor\HTMLEditorField:
  extensions:
    - Sheadawson\Shortcodable\Extensions\ShortcodableHtmlEditorField

SilverStripe\View\Parsers\ShortcodeParser:
  extensions:
    - Sheadawson\Shortcodable\Extensions\ShortcodableShortcodeParserExtension
